name: 'assign-oncall-prep-issue'
description: "GitHub Action that assigns an issue to next week's oncall engineers"
author: 'Brian Cristante'
# inputs:
runs:
  using: 'node12'
  main: 'dist/index.js'
