name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - dev
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run pack
    - run: npm run test
      env:
        PAGERDUTY_API_KEY: ${{ secrets.PAGERDUTY_API_KEY }}
        PAGERDUTY_SCHEDULE_ID: PVHAB95

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        scheduleId: PVHAB95
        pagerDutyToken: ${{ secrets.PAGERDUTY_API_KEY }}
